"""add conversations title_is_auto column

Revision ID: 1316cdf293dd
Revises: d3769d212694
Create Date: 2026-07-24 12:45:41.635159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1316cdf293dd'
down_revision: Union[str, None] = 'd3769d212694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate always proposes dropping ix_conversations_user_updated and
    # ix_messages_conversation_created here - see prior migrations for why they're kept.
    # server_default='true' only to satisfy the NOT NULL constraint while adding this column to
    # a table with existing rows - immediately backfilled to false below and then dropped, since
    # the ORM-level Python default (True) is what actually governs new rows going forward.
    op.add_column('conversations', sa.Column('title_is_auto', sa.Boolean(), nullable=False, server_default='true'))
    # Existing conversations already have concrete titles (auto-truncated or manually renamed) -
    # treat them all as "not auto" so this migration can't retroactively make an old
    # conversation's title eligible for the new fire-and-forget AI-title overwrite it never
    # opted into.
    op.execute("UPDATE conversations SET title_is_auto = false")
    op.alter_column('conversations', 'title_is_auto', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'title_is_auto')
    # ### end Alembic commands ###
