"""add user role column

Revision ID: 1e071dc0c7bf
Revises: 2f16f7837d5e
Create Date: 2026-07-23 18:41:18.291825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e071dc0c7bf'
down_revision: Union[str, None] = '2f16f7837d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate always proposes dropping ix_conversations_user_updated and
    # ix_messages_conversation_created here - see prior migrations for why they're kept.
    # server_default='user' so this NOT NULL column can be added to a table that already has
    # rows; also left in place afterward as a DB-level backstop alongside the ORM's default.
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    op.create_check_constraint('ck_users_role', 'users', "role IN ('user','admin')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_role', 'users', type_='check')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
