"""add conversation share_token

Revision ID: 2f16f7837d5e
Revises: 1958bd3ff4cf
Create Date: 2026-07-23 14:20:35.374506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f16f7837d5e'
down_revision: Union[str, None] = '1958bd3ff4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('share_token', sa.String(length=43), nullable=True))
    # NOTE: autogenerate always proposes dropping ix_conversations_user_updated and
    # ix_messages_conversation_created here - see prior migrations for why they're kept.
    op.create_index(op.f('ix_conversations_share_token'), 'conversations', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_share_token'), table_name='conversations')
    op.drop_column('conversations', 'share_token')
    # ### end Alembic commands ###
