"""add google credentials table

Revision ID: 462bc04596b7
Revises: 327f965d5518
Create Date: 2026-07-27 02:57:06.095371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '462bc04596b7'
down_revision: Union[str, None] = '327f965d5518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.String(length=500), nullable=False),
    sa.Column('google_email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # NOTE: autogenerate also proposed dropping apscheduler_jobs (owned/created by APScheduler
    # itself at runtime, not by an Alembic migration - see app/core/scheduler.py) and two
    # pre-existing, unrelated drifted indexes (ix_conversations_user_updated,
    # ix_messages_conversation_created). Deliberately left out of this migration, same as the
    # 327f965d5518 migration that first hit the index drift.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_credentials')
    # ### end Alembic commands ###
