"""add last_login_method to users

Revision ID: 53390e8feaa6
Revises: c0af4d48c1b7
Create Date: 2026-08-04 21:41:54.606717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '53390e8feaa6'
down_revision: Union[str, None] = 'c0af4d48c1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed dropping the apscheduler_jobs table and re-creating a
    # couple of indexes/constraints under new names - pre-existing drift, unrelated to this
    # feature (same note as every prior migration this session, e.g. c0af4d48c1b7's).
    op.add_column('users', sa.Column('last_login_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_method')
    # ### end Alembic commands ###
