"""add is_resume to documents

Revision ID: b4f7d9843a0f
Revises: f4a7c2e91b06
Create Date: 2026-08-01 23:27:14.943607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b4f7d9843a0f'
down_revision: Union[str, None] = 'f4a7c2e91b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed dropping the apscheduler_jobs table and re-creating a
    # couple of indexes/constraints under new names - pre-existing drift, unrelated to this
    # feature (same as f4a7c2e91b06's note). Deliberately left out of this migration.
    op.add_column('documents', sa.Column('is_resume', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_resume')
    # ### end Alembic commands ###
