"""add citations to messages

Revision ID: c0af4d48c1b7
Revises: b4f7d9843a0f
Create Date: 2026-08-02 12:38:23.162302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c0af4d48c1b7'
down_revision: Union[str, None] = 'b4f7d9843a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed dropping the apscheduler_jobs table and re-creating a
    # couple of indexes/constraints under new names - pre-existing drift, unrelated to this
    # feature (same as f4a7c2e91b06's and b4f7d9843a0f's notes). Deliberately left out.
    op.add_column('messages', sa.Column('citations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'citations')
    # ### end Alembic commands ###
