"""add linkedin_credentials table

Revision ID: c1f2a9d84e33
Revises: 8808b782c857
Create Date: 2026-07-29 22:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f2a9d84e33'
down_revision: Union[str, None] = '8808b782c857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.String(length=2000), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('linkedin_name', sa.String(length=255), nullable=True),
    sa.Column('linkedin_email', sa.String(length=255), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # NOTE: autogenerate also proposed dropping ix_conversations_user_updated and
    # ix_messages_conversation_created here - pre-existing drift between the live DB and the
    # current model files, unrelated to this feature. Deliberately left out of this migration
    # rather than silently dropping indexes an unrelated feature has no business touching.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linkedin_credentials')
    # ### end Alembic commands ###
