"""add messages agent column

Revision ID: d3769d212694
Revises: 1e071dc0c7bf
Create Date: 2026-07-24 12:14:43.051623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3769d212694'
down_revision: Union[str, None] = '1e071dc0c7bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate always proposes dropping ix_conversations_user_updated and
    # ix_messages_conversation_created here - see prior migrations for why they're kept.
    op.add_column('messages', sa.Column('agent', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'agent')
    # ### end Alembic commands ###
